spring.application.name=registry-service


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=registry-service
server.port=8761


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

management.observations.key-values.application=${spring.application.name}


management.prometheus.metrics.export.enabled=true


management.tracing.sampling.probability=1.0

management.otlp.tracing.endpoint=http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317

management.metrics.tags.application=${spring.application.name}
