grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          access: proxy
          isDefault: true
          version: 1

        - name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          access: proxy
          isDefault: false
          jsonData:
            derivedFields:
              - datasourceUid: tempo
                matcherRegex: "traceId[=:]\\s*(\\w+)"
                name: TraceID
                url: $${__value.raw}
            maxLines: 1000
          version: 1

        - name: Tempo
          type: tempo
          url: http://tempo.monitoring.svc.cluster.local:3100
          access: proxy
          isDefault: false
          jsonData:
            tracesToLogs:
              datasourceUid: Loki
              tags: ["job", "instance", "pod", "namespace"]
              mappedTags:
                - key: service.name
                  value: app
              spanStartTimeShift: "-5m"
              spanEndTimeShift: "5m"
              filterByTraceID: true
              filterBySpanID: false
            tracesToMetrics:
              datasourceUid: Prometheus
              tags:
                - key: service.name
                  value: service
            serviceMap:
              datasourceUid: Prometheus