apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  namespace: monitoring
  labels:
    release: monitoring 
spec:

  namespaceSelector:
    any: true 
  selector:
    matchLabels:
      metrics: dev-monitor 
  endpoints:
  - port: http 
    path: /actuator/prometheus
    interval: 30s