apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-db-superuser
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: auth-db-superuser
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth  
      data:
        username: "{{ .AUTH_SERVER_DB_USER }}"
        password: "{{ .AUTH_SERVER_DB_PASSWORD }}"
  data:
    - secretKey: AUTH_SERVER_DB_USER
      remoteRef:
        key: secret/auth-service
        property: AUTH_SERVER_DB_USER
    
    - secretKey: AUTH_SERVER_DB_PASSWORD
      remoteRef:
        key: secret/auth-service
        property: AUTH_SERVER_DB_PASSWORD