apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-server
  ports:
    - port: 8081
      targetPort: 8081
#defaults to ClusterIP btw. Exposes service only inside a cluster through auth-service.default.svc.cluster.local. NodePort exposes it outside