apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: samnayak1/auth-server:1.0.29
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

          resources:
            limits:
              memory: "768Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"

          readinessProbe:  #has the app started
            httpGet:
              path: /actuator/health/readiness  
              port: 8081
            initialDelaySeconds: 30  
            periodSeconds: 10        
            timeoutSeconds: 5    
            successThreshold: 1      
            failureThreshold: 3     
         
          livenessProbe:  #is the app running
            httpGet:
              path: /actuator/health/liveness   
              port: 8081
            initialDelaySeconds: 60 
            periodSeconds: 15      
            timeoutSeconds: 5      
            failureThreshold: 3     
          
         
          startupProbe: #delays liveness checks until the pod succeeds
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          env:
            - name: SERVER_PORT
              value: "8081"
       

            - name: AUTH_SERVER_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: AUTH_SERVER_DB
            - name: AUTH_SERVER_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: AUTH_SERVER_POSTGRES_HOST

  

            
            - name: CATALOG_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: CATALOG_SERVICE_HOST

            - name: BID_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: BID_SERVICE_HOST

  
            - name: GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: GATEWAY_URL

              


            - name: AUTH_SERVER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: AUTH_SERVER_DB_PASSWORD
            - name: AUTH_SERVER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: AUTH_SERVER_DB_USER

            - name: JWT_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: JWT_ISSUER_URI

            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: AWS_REGION


            - name: AWS_COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: AWS_COGNITO_USER_POOL_ID


            - name: AWS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: AWS_CLIENT_ID


            - name: AWS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: AWS_CLIENT_SECRET

            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: AWS_ACCESS_KEY

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: STRIPE_SECRET_KEY

            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: STRIPE_PUBLISHABLE_KEY

            

                
