apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: auth-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: AUTH_SERVER_DB_PASSWORD
      remoteRef:
        key: secret/auth-service
        property: AUTH_SERVER_DB_PASSWORD

    - secretKey: AUTH_SERVER_DB_USER
      remoteRef:
        key: secret/auth-service
        property: AUTH_SERVER_DB_USER

    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: secret/auth-service
        property: KEYCLOAK_ADMIN

    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: secret/auth-service
        property: KEYCLOAK_ADMIN_PASSWORD

    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: secret/auth-service
        property: KEYCLOAK_CLIENT_SECRET

    - secretKey: KEYCLOAK_POSTGRES_PASSWORD
      remoteRef:
        key: secret/auth-service
        property: KEYCLOAK_POSTGRES_PASSWORD
