apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: auth-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: AUTH_SERVER_DB_PASSWORD
      remoteRef:
        key: secret/auth-service
        property: AUTH_SERVER_DB_PASSWORD

    - secretKey: AUTH_SERVER_DB_USER
      remoteRef:
        key: secret/auth-service
        property: AUTH_SERVER_DB_USER



    - secretKey: JWT_ISSUER_URI
      remoteRef:
        key: secret/auth-service
        property: JWT_ISSUER_URI

    - secretKey: AWS_REGION
      remoteRef:
        key: secret/auth-service
        property: AWS_REGION

    - secretKey: AWS_COGNITO_USER_POOL_ID
      remoteRef:
        key: secret/auth-service
        property: AWS_COGNITO_USER_POOL_ID

    - secretKey: AWS_CLIENT_ID
      remoteRef:
        key: secret/auth-service
        property: AWS_CLIENT_ID

    - secretKey: AWS_CLIENT_SECRET
      remoteRef:
        key: secret/auth-service
        property: AWS_CLIENT_SECRET

    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: secret/payment-gateway-secret
        property: STRIPE_SECRET_KEY

    - secretKey: STRIPE_PUBLISHABLE_KEY
      remoteRef:
        key: secret/payment-gateway-secret
        property: STRIPE_PUBLISHABLE_KEY

    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: secret/payment-gateway-secret
        property: STRIPE_WEBHOOK_SECRET





