apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-superuser
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-db-superuser
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth  
      data:
        username: "{{ .POSTGRES_USER }}"
        password: "{{ .POSTGRES_PASSWORD }}"
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/keycloak-service
        property: POSTGRES_USER
    
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/keycloak-service
        property: POSTGRES_PASSWORD