
spring.application.name=api-gateway
server.port=8084



spring.cloud.discovery.enabled=true

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_HOST}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

# Catalog Service
spring.cloud.gateway.server.webflux.routes[1].id=CATALOG-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=${CATALOG_SERVICE_HOST}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/categories/**, /api/v1/items/**

# Bid Service
spring.cloud.gateway.server.webflux.routes[2].id=BID-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=${BID_SERVICE_HOST}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/bids/**

# Auth Service - Swagger
spring.cloud.gateway.server.webflux.routes[3].id=AUTH-SERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[3].uri=${AUTH_SERVICE_HOST}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/auth/v3/api-docs
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=1

# Catalog Service - Swagger
spring.cloud.gateway.server.webflux.routes[4].id=CATALOG-SERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[4].uri=${CATALOG_SERVICE_HOST}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/catalog/v3/api-docs
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=1

# Bid Service - Swagger
spring.cloud.gateway.server.webflux.routes[5].id=BID-SERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[5].uri=${BID_SERVICE_HOST}
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/bid/v3/api-docs
spring.cloud.gateway.server.webflux.routes[5].filters[0]=StripPrefix=1

# Swagger UI Aggregator Settings
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=Catalog Service
springdoc.swagger-ui.urls[1].url=/catalog/v3/api-docs
springdoc.swagger-ui.urls[2].name=Bid Service
springdoc.swagger-ui.urls[2].url=/bid/v3/api-docs


resilience4j.circuitbreaker.instances.bidService.register-health-indicator=true
resilience4j.circuitbreaker.instances.bidService.sliding-window-size=10
resilience4j.circuitbreaker.instances.bidService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.bidService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.bidService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.bidService.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.catalogService.register-health-indicator=true
resilience4j.circuitbreaker.instances.catalogService.sliding-window-size=10
resilience4j.circuitbreaker.instances.catalogService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.catalogService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.catalogService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.catalogService.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.authService.register-health-indicator=true
resilience4j.circuitbreaker.instances.authService.sliding-window-size=10
resilience4j.circuitbreaker.instances.authService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.authService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.authService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.authService.failure-rate-threshold=50



management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always


management.prometheus.metrics.export.enabled=true


management.metrics.tags.application=${spring.application.name}
management.observations.key-values.application=${spring.application.name}


logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]



app.cors.allowed-origins=${ALLOWED_CLIENT_HOSTS}

spring.main.web-application-type=reactive



spring.data.redis.host=my-valkey
spring.data.redis.port=6379
spring.data.redis.password=${valkey-password}
spring.cache.type=redis

rate-limit.window-size-seconds=${RATE_LIMIT_WINDOW_SIZE_SECONDS}
rate-limit.max-requests=${RATE_LIMIT_MAX_REQUESTS}