apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bid-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: bid-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
  
        KAFKA_USERNAME: "{{ .KAFKA_USERNAME }}"
        KAFKA_PASSWORD: "{{ .KAFKA_PASSWORD }}"
        POSTGRES_DB: "{{ .POSTGRES_DB }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
 
        KAFKA_CLIENT_JAAS_CONFIG: |
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="{{ .KAFKA_USERNAME }}"
          password="{{ .KAFKA_PASSWORD }}";

  data:
    - secretKey: KAFKA_USERNAME
      remoteRef:
        key: secret/bid-service
        property: KAFKA_USERNAME

    - secretKey: KAFKA_PASSWORD
      remoteRef:
        key: secret/bid-service
        property: KAFKA_PASSWORD

    - secretKey: POSTGRES_DB
      remoteRef:
        key: secret/bid-service
        property: POSTGRES_DB

    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/bid-service
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/bid-service
        property: POSTGRES_PASSWORD

