apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-server
  labels:
    app: catalog-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-server
  template:
    metadata:
      labels:
        app: catalog-server
    spec:
      containers:
      - name: catalog-server-container
        image: samnayak1/catalogbackend:1.0.0 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
  
        env:
        - name: SERVER_PORT
          value: "8085"

        - name: POSTGRES_HOST
                                    
          valueFrom:
            configMapKeyRef:
              name: catalog-config-map      
              key: POSTGRES_HOST 
        - name: EUREKA_HOST
          valueFrom:
            configMapKeyRef:
              name: catalog-config-map      
              key: EUREKA_HOST


        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: catalog-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-secret
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: catalog-secret
              key: POSTGRES_DB
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: catalog-secret
              key: AWS_ACCESS_KEY
        - name: AWS_BUCKET_REGION
          valueFrom:
            secretKeyRef:
              name: catalog-secret
              key: AWS_BUCKET_REGION
        - name: AWS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: catalog-secret
              key: AWS_BUCKET_NAME
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: catalog-secret
              key: AWS_SECRET_ACCESS_KEY

          