apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-db
  labels:
    app: catalog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest 
        ports:
        - containerPort: 5432
        command:
          - postgres
          - -c
          - hba_file=/etc/postgresql/custom-pg_hba.conf
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql
        - name: custom-config
          mountPath: /etc/postgresql
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: POSTGRES_DB

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: catalog-db-pvc
      - name: custom-config
        configMap:
          name: postgres-custom-config
          