apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-db-pvc
spec:
  accessModes:
    - ReadWriteOnce #only allows one node to mount to this volume
  resources:
    requests:
      storage: 2Gi