apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-jaas-config
  namespace: kafka
spec:
  refreshInterval: 1h
  # Every 1 hour, re-read the secret values from the external provider (Vault) and sync them into Kubernetes.
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafka-jaas-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        kafka_server_jaas.conf: |
          KafkaServer {
            org.apache.kafka.common.security.plain.PlainLoginModule required
            user_admin="{{ .admin_password }}"
            user_producer="{{ .producer_password }}"
            user_consumer="{{ .consumer_password }}"
            user_broker="{{ .broker_password }}";
          };

          Client {
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username="broker"
            password="{{ .broker_password }}";
          };
  data:
    - secretKey: admin_password
      remoteRef:
        key: secret/kafka/jaas
        property: admin_password
    - secretKey: producer_password
      remoteRef:
        key: secret/kafka/jaas
        property: producer_password
    - secretKey: consumer_password
      remoteRef:
        key: secret/kafka/jaas
        property: consumer_password
    - secretKey: broker_password
      remoteRef:
        key: secret/kafka/jaas
        property: broker_password

