---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-jaas-config
  namespace: kafka
spec:
  encryptedData:
    kafka_server_jaas.conf: AgBWrf1HY8xCoVHJdL2Fs5PkLSm3e8OG5D3Z++ejjO8Q+W3XkChoZDzWOIJhTABGE5NZUM3H0mkMuKKswXZUuZbdH68UAVhDTOG+EMKXNooZxRNCsMb6Lwu7tkj4t+q6bPK0YdN2IHyPEQC6NvBcgrulfsIx5Cd5ehXK9eUdwiquNDP5wKzy2DJV84MPC+Ni0rcVpzbAKf+/q8UkW/rufHpg5b7EjDNqLbxWje/wgUkxWqsHuTqhYEVkD6l/a1Iz22cEwjRuI7XMHZdRnZnq/AELiUAlCRSyd0HcOie0zvfrIGKuGeZG/2dJIMsZPuFO1tmFJQ2HxaX75r1vBexaY/QS85Ra0M6RRXgLZ2JMQe5Awce22GN9Wwlxe/OoZZUR1XuPLtgx+9dbqie8uQd9SiYyV+KHogg8SAnthCAcCfVSMCziWFrm3QcPxdXiCIrUqJYVdLuu4f5cO1X1/pjUu7+LbpE058qK0I1XdTN+x+r09UNpJ7PjjvfNgQCcYgfZYLgynG0KlfFQCJbzMeToEo/i81HtZLJB8npkOd98Sd3G/qt3JQNv9jjSvPABki3IU4OGoYlTb2foUUT9TcBHPEiDYjXmohwwSkEnHyVCnIFtaRh0PvWDg4ypQSRAqBGUeNPkW21KKZ2ms5bBFG8Suujo1T/xEDXRTxBIEPE4Dm873JU73nUic2VkhKkom1pLPUvQ+Nvd3mZmJmzrsEjIQOrKUZCjS9cJDkhkbYe1KFkN+P26hbUeKO0IjY/HadnoPHKLoeWgETnNRCDs1Cpq+PfHRnB1ggLebWxUL3UriAzDpsjwChxPQ8skvSx7Za+SYDDQjFbog/X9DdP1ZxEBUh8UqKafQH0nF97qUHABuLUHEsQTjhC52AkQ1JqrciPymH/vI0ZFIMHx8rdeJcw1hnkods8T7pgbXSxR/qHxbCHouCFUSFJQJVHRoKEtiUdXszzNz0U+MMabC2tYQGc8Rmii4nQ2DeZa8ztwShgHXTvl2MCeCS9StVVy0kA25Ga3S+vXhFl6M6YnCjIfu3+qfBegQXadlur27aK6DYpsUP/7s9cXSr+BuNtEO77NOCQ2oLAP+JmUeL6C5bMOhwNfTrQjUtsZb/mcTVgLBvU0RHbDTMM5jTJH2AujrHSvmuh+recn1hfAOiyICWIJaWuFTQPWoybvaOybKUARGFX2MKJlNOUcJhas0qUzQtgLLc+mA4Fy0Wymg0A+VyVbUF4nY7iYxu8FGm9dKfXbeGaHZ7o0ku7JkXAUwGEWM4If/v0ndvpZuM0wnvwCbnZGPOLf/xeQnZvf2YupwDXyChPNkQ301YMRQZPVmQlI17Zh7dISG1OFu6u8zpxyjiVS
  template:
    metadata:
      name: kafka-jaas-config
      namespace: kafka
    type: Opaque
