apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-consumer-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
    # What Kubernetes Secret should I create or manage from the external data?
  target:
    name: kafka-consumer-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/kafka/consumer
        property: username
    - secretKey: password
      remoteRef:
        key: secret/kafka/consumer
        property: password
