apiVersion: v1
kind: ConfigMap
metadata:
  name: websocket-service-config
  labels:
    app: websocket-service-config
data:
  KAFKA_BROKER: kafka-service.kafka.svc.cluster.local:9092

  APP_NAME: WEBSOCKET-SERVICE
  HOST_NAME: websocket-service
  KAFKA_SASL_MECHANISM: plain


  

