---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-consumer-credentials
  namespace: default
spec:
  encryptedData:
    password: AgC6+JGQxsLnG7IIkmzw1RlHeqI2WJanOM+henfVpL3tgb0vDGtkqvFJBuvu8I0vg+rOQ7kpOuQ/bRm0YFjz9K81HGIhh9g2lWlkvgFRXJTnLb+JW+2DkVUXklPEL7Mk0bijemvTnU56naRa29e7TuMEFg7N0XYGyPABIcN2RqFLfta9CzhLpt66qjmIK7SocjROazE7/twmUZ6z0mNSZO4l7/8ee7E4BQ3KFnGnKwjkE8OmZJN7/TXj2b4UFWZ318+dJw82lJ2r1AJQeYACQ8FV0ERME7cX6Sfg6/4EMu1+CtKYx50XNgc5owa+UD6DyBeJmMOSSolrQH6uh6+jxXWA4XWX96sXxG4kFimhfXKYO1JMb0J3LTS41hrmfQvySlcvD/16CY3Gv6Figz9b+OgKzM0gxJV9CUWW0Jg0W4enL9DCVa6SVwyJrBcyHp8CQSEdbC6pbM/Ye31xN6B5fpfOUzTYfD2hDe9SPfiZ7GxyLTi2a5K3LP93wyuhfjxE1x6dD6DhYeF7lZuGiVdUMGRLE6a9Kui+suwPOJDuOQsrDt51tkA0nSvcGnlOkuJvqY8cH1bfkqkMW3S4C2CJDepthdwu6LCMTFSMe6gMF4LF6HKXbfbC4U59Eu4YI9iQz6eQSoES/oCe4TSHhjg+HBXfYzTgDZrquUdLgFIehPH6RSoPPIcsxIUVLSmA3zJY90PYp94wDO+u9rJ2jhl5k0yZTm9dzWVdS37wMHj9Aan+B+Qfup4MRVETQvGuRg==
    username: AgDQXE/Kyh3PBXU+KmnHimv1wapzK54emMx378zzAgVdPVCn0M5IUeGU/nIyr5GbUuzzWPEX/gdB0yzV+ZBlRbTpTsAbeU3v7jmuHFOKR6TaiO97W/3VfX/l23usv7r53cJzKXgxbLbQX4kJLoJSEU/BRgtF1U87NaQMpmw0XIMo5NEOzbkvz1Ib7lESf5I9FLkq0JLJDla80wDuTYrEP/nQUaaq6XhMJyfoI7pEXQjCDKNMHWXimoKk9U7Pd8kZkFNdVlSGKS/Yw7xePTdi3tWraXAbYDF/lf2VDx82wJo9jYubVbW50D2wQgiKYmBGALG4fT/xUgM/hTfbJ5hPFET8Htk9LSGTdWKI5HBw2e6b8JnwmXnrYAN428lsnjaIQGSGVBaXZTW2yBvLGekOzb27Y7qpNVsEApi2ul46LRLoylS2n6J/EoB+cDCg8bSOyLHy0HyjKw6k8cWSL2zJwVTmbJjx6pepujoUQFtooAxWiDp+UqJewThDLdiy1d74sLm9ME+rchVXEKWfCL/3XZoC0BFvpzfjY9fPK+dnPgUIuy1W2nOMZQ7pkIN1HJCRViau/5lU37YUNZFINrjgCXDR4d3tD5l6OQs0M/KNFBIpoCgIybecL6fghm5hIyD0i0wZN2Iw5eScV6D05Dj32tsqeUFlfVpSO7UdGxTzdxrA4If00W/WAbaLKq8ZcKM0H5LWWkGLQC3OJA==
  template:
    metadata:
      name: kafka-consumer-credentials
      namespace: default
    type: Opaque
