services:
  bid_server:
    image: bidservice
    build: .
    ports:
      - "8082:8082" 
    env_file:
      - .env 
    networks:
      - mynetwork
    environment:
      - SERVER_PORT=8082

networks:
  mynetwork:
    driver: bridge