services:
  bid_server:
    image: bidservice
    build: .
    ports:
      - "8080:8080"  
    networks:
      - mynetwork
    environment:
      - SERVER_PORT=8080 

networks:
  mynetwork:
    driver: bridge