services:
  registry-server:
    image: registryservice
    build: .
    env_file:
      - .env
    ports:
      - "8761:8761"  
    networks:
      - mynetwork
    environment:
      - SERVER_PORT=8761 

networks:
  mynetwork:
    driver: bridge