services:
  catalog_db:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - postgresData:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
       - POSTGRES_DB=${POSTGRES_DB}
       - POSTGRES_USER=${POSTGRES_USER}
       - PGUSER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PWD}     
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
  
  catalog_server:
    image: catalogbackend
    build: .
    depends_on: 
      catalog_db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"  
    networks:
      - mynetwork
    environment:
      - SERVER_PORT=8080 

networks:
  mynetwork:
    driver: bridge
 
volumes:
  postgresData:
  cache:
    driver: local