apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  EUREKA_HOST: http://registry-service:8761
  AUTH_SERVICE_HOST: http://auth-service:8081
  CATALOG_SERVICE_HOST: http://catalog-server-service:8085
  BID_SERVICE_HOST: http://bid-server-service:8082