package com.nilami.catalogservice.dto;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

import java.time.Instant;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.stream.Collectors;



import com.nilami.catalogservice.models.Item;
import com.nilami.catalogservice.services.serviceAbstractions.FileUploadService;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ItemDTO {


    private UUID id;

    private String title;

    private String description;

    private BigDecimal basePrice;

    private String brand;

    private String creatorUserId;

    private List<String> pictureIds;

    private UUID categoryId;

    private Date expiryTime;

    private Instant createdAt;

    private Instant updatedAt;

    private boolean deleted;

    public static ItemDTO toItemDTO(Item item,FileUploadService fileService) {
        return ItemDTO.builder()
                .id(item.getId())
                .title(item.getTitle())
                .description(item.getDescription())
                .basePrice(item.getBasePrice())
                .brand(item.getBrand())
                .creatorUserId(item.getCreatorUserId())
                .pictureIds(item.getPictureIds().stream()
                    .map(pictureId -> {
                        try {
                            return fileService.generateDownloadPresignedUrl(item.getId()+"/"+pictureId).toString();
                        } catch (Exception e) {
                            return null;
                        }
                    })
                    .filter(Objects::nonNull) // Let's say the picture id cannot be generated by aws, then filter out null values
                    .collect(Collectors.toList()))
                .categoryId(item.getCategory() != null ? item.getCategory().getId() : null)
                .expiryTime(item.getExpiryTime())
                .createdAt(item.getCreatedAt())
                .updatedAt(item.getUpdatedAt())
                .deleted(item.isDeleted())
                .build();
    }
}
