services:
  auth_server:
    image: authservice
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"  
    networks:
      - mynetwork
    environment:
      - SERVER_PORT=8081

networks:
  mynetwork:
    driver: bridge